version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres-4
    environment:
      POSTGRES_USER: #TODO
      POSTGRES_PASSWORD: #TODO
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pg_data3:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - platform

networks:
  platform:
    external: true