tg:
  bot_token: 7060104792:AAHUmMq2AY8UsPKhvHVP-1H4Bm-bRko4Om0
  bot_name: CurrencyBot
google:
  application_name: My Project 8196
  token_directory_path: tokens
  credentials_file_path: /credentials.json
  family_directory_id: 1cHnMg8C6-RRHD2L8xKUvaEqTSsyt5dOu